apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsbymatthew-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: appsbymatthew-ui
  template:
    metadata:
      labels:
        app: appsbymatthew-ui
    spec:
      containers:
      - image: mfarmer5102/appsbymatthew-ui:master
        name: appsbymatthew-ui
        ports:
        - containerPort: 80
